---
title: "plot"
author: "Yinuo Jin"
output: pdf_document
---

```{r}
library(torch)
library(caret)
library(ggplot2)
library(dplyr)
library(gridExtra)
```


```{r}
data <- read.csv("../data/processed_counts.csv", row.names = 1).
head(data)
```

```{r}
annot <- read.csv("../data/annotation.csv", row.names = 1)
head(annot)
```



```{r}
library(Seurat)
```


```{r}
bulk <- CreateSeuratObject(counts = t(data), project = "bulk_classify")
bulk
```

```{r}
bulk <- ScaleData(bulk, features = colnames(data))
bulk <- RunPCA(bulk, features = colnames(data))
```


```{r}
VizDimLoadings(bulk, dims = 1:2, reduction = "pca")
```


```{r}
bulk$Type <- annot$Type
bulk$Type.bin <- ifelse(annot$Type != "Normal", "Tumor", "Normal")
```

```{r fig.width = 6, fig.height = 5}
q.pca.bin <- DimPlot(bulk, reduction = "pca", group.by = "Type.bin") + 
         ggtitle("PCA") +
         theme(plot.title = element_text(hjust = 0.5))
q.pca.bin
```

```{r fig.width = 6, fig.height = 5}
q.pca <- DimPlot(bulk, reduction = "pca", group.by = "Type") + 
         ggtitle("PCA (Pan-cancer)") +
         theme(plot.title = element_text(hjust = 0.5))
q.pca
```


#### Run UMAP
```{r}
bulk <- RunUMAP(bulk, dims = 1:10)
```

```{r fig.width = 6, fig.height = 5}
q.umap.bin <- DimPlot(bulk, reduction = "umap", group.by = "Type.bin") + 
          ggtitle("UMAP") +
          theme(plot.title = element_text(hjust = 0.5))
q.umap.bin
```

```{r fig.width = 6, fig.height = 5}
q.umap <- DimPlot(bulk, reduction = "umap", group.by = "Type") + 
          ggtitle("UMAP (Pan-cancer)") +
          theme(plot.title = element_text(hjust = 0.5))
q.umap
```

```{r}
bulk <- RunTSNE(bulk, dims = 1:10)
```


```{r fig.width = 6, fig.height = 5}
q.tsne.bin <- DimPlot(bulk, reduction = "tsne", group.by = "Type.bin") + 
          ggtitle("t-SNE") +
          theme(plot.title = element_text(hjust = 0.5))
q.tsne.bin
```

```{r fig.width = 6, fig.height = 5}
q.tsne <- DimPlot(bulk, reduction = "tsne", group.by = "Type") + 
          ggtitle("t-SNE (Pan-cancer)") +
          theme(plot.title = element_text(hjust = 0.5))
q.tsne
```


```{r fig.width = 18, fig.height = 10}
grid.arrange(q.pca.bin, q.tsne.bin, q.umap.bin,
             q.pca, q.tsne, q.umap, 
             nrow = 2, ncol = 3)
```

```{r}
q.dr <- arrangeGrob(q.pca.bin, q.tsne.bin, q.umap.bin,
                    q.pca, q.tsne, q.umap,
                    nrow = 2, ncol = 3)

ggsave("../slides+report/dim_reduction.png", q.dr, width = 18, height = 10)
```


### Visualize other ML results
```{r}
source("utils.R")
```


```{r}
lbls <- sort(unique(annot$Type))
```

#### k-NN
```{r}
knn.bin <- as.matrix(rbind(c(150, 16), c(8, 1736)))
rownames(knn.bin) <- c("Normal", "Tumor")
colnames(knn.bin) <- c("Normal", "Tumor")

cm.knn.bin <- confusionMatrix(knn.bin, dnn = c("prediction", "reference"))
cm.knn.bin
```

```{r fig.width = 4, fig.height = 3}
q1 <- visualizeConfusionMat(cm.knn.bin, name = colnames(knn.bin), title = "Binary (k-NN)")
q1
```

```{r}
ggsave("../slides+report/knn_cm_bin.png", q1, width = 4, height = 3.5)
```


```{r}
knn.pan <- as.matrix(
  rbind(
    c(85, 1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 2),
    c(1, 268,0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 0, 0),
    c(3, 0, 70, 0, 0, 12,0, 0, 4, 0, 0, 0, 0, 0, 0, 0),
    c(1, 0, 0, 89, 0, 0, 0, 1, 0, 0, 0, 31,0, 5, 0, 0),
    c(1, 0, 0, 0, 43, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0),
    c(4, 1, 4, 0, 0, 119,0, 0, 10,0, 0, 0, 1, 2, 0, 0),
    c(0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0,132,12, 0, 0, 0, 0, 0 ,0, 2),
    c(0, 0, 1, 0, 0, 7, 0, 3,111, 0, 0, 0, 0, 0, 0, 0),
    c(0, 3, 0, 1, 0, 0, 2, 3, 1,152, 2, 0, 0, 0, 5, 1),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 3,125, 0, 0, 0, 0, 0),
    c(0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0,13, 0, 0, 0, 0),
    c(2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 108,0, 0, 1),
    c(0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 88, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120,0),
    c(1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 141)
  )
)

rownames(knn.pan) <- lbls
colnames(knn.pan) <- lbls

cm.knn.pan <- confusionMatrix(knn.pan, dnn = c("prediction", "reference"))
cm.knn.pan
```

```{r fig.width = 8, fig.height = 8}
q2 <- visualizeConfusionMat(cm.knn.pan, name = colnames(knn.pan), title = "Pan-cancer (k-NN)")
q2
```

```{r}
ggsave("../slides+report/knn_cm_pan.png", q2, width = 8, height = 8)
```


#### Naive Bayes
```{r}
nb.bin <- as.matrix(rbind(c(145, 103), c(13, 1649)))
rownames(nb.bin) <- c("Normal", "Tumor")
colnames(nb.bin) <- c("Normal", "Tumor")

cm.nb.bin <- confusionMatrix(nb.bin, dnn = c("prediction", "reference"))
cm.nb.bin
```

```{r fig.width = 4, fig.height = 3}
q1 <- visualizeConfusionMat(cm.nb.bin, name = colnames(nb.bin), title = "Binary (Naive Bayes)")
q1
```

```{r}
ggsave("../slides+report/nb_cm_bin.png", q1, width = 4, height = 3.5)
```



```{r}
nb.pan <- as.matrix(
  rbind(
    c(74, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0),
    c(0, 254,0, 0, 0, 0, 0, 0, 0, 2, 4, 0, 0, 0, 0, 0),
    c(13, 1,63, 0, 0, 11,0, 1, 7, 0, 0, 0, 0, 0, 0, 1),
    c(0, 0, 0, 55, 0, 0, 0, 0, 0, 0, 0, 8, 0, 6, 0, 0),
    c(0, 0, 0, 0, 43, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0),
    c(5, 1, 4, 0, 0, 108,0, 0, 8, 4, 0, 0, 1, 1, 0, 0),
    c(0, 0, 0, 0, 0, 0, 80, 0, 0,22, 0, 0, 0, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 1,124,10, 0, 0, 0, 0, 0, 2, 0),
    c(1, 4, 6, 0, 0,18, 1, 7,114, 0, 0, 0, 0, 1, 0, 0),
    c(2, 8, 0, 0, 0, 1, 2, 7, 1,114, 2, 0, 0, 4, 1, 2),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 4,121, 0, 0, 0, 0, 0),
    c(0, 0, 0,46, 0, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,108, 0, 0, 1),
    c(2, 2, 0, 6, 0, 0, 1, 0, 1, 2, 0, 1, 0, 84, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 122,0),
    c(1, 2, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 143)
  )
)

rownames(nb.pan) <- lbls
colnames(nb.pan) <- lbls

cm.nb.pan <- confusionMatrix(nb.pan, dnn = c("prediction", "reference"))
cm.nb.pan
```

```{r fig.width = 8, fig.height = 8}
q2 <- visualizeConfusionMat(cm.nb.pan, name = colnames(knn.pan), title = "Pan-cancer (Naive Bayes)")
q2
```
```{r}
ggsave("../slides+report/nb_cm_pan.png", q2, width = 8, height = 8)
```


### SVM
Linear
```{r}
lsvm.bin <- as.matrix(rbind(c(154, 12), c(4, 1740)))
rownames(lsvm.bin) <- c("Normal", "Tumor")
colnames(lsvm.bin) <- c("Normal", "Tumor")

cm.lsvm.bin <- confusionMatrix(lsvm.bin, dnn = c("prediction", "reference"))
cm.lsvm.bin
```

```{r fig.width = 4, fig.height = 3}
q1 <- visualizeConfusionMat(cm.lsvm.bin, name = colnames(lsvm.bin), title = "Binary (linear-SVM)")
q1
```

```{r}
ggsave("../slides+report/lsvm_cm_bin.png", q1, width = 4, height = 3.5)
```


```{r}
lsvm.pan <- as.matrix(
  rbind(
    c(95, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1),
    c(0, 268,0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0),
    c(1, 0, 76, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0),
    c(0, 0, 0, 94, 0, 0, 0, 0, 0, 0, 0, 22,0, 0, 0, 0),
    c(0, 0, 0, 0, 43, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0),
    c(2, 0, 0, 0, 0, 132,0, 0, 5, 0, 0, 0, 1, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0,138, 9, 1, 0, 0, 0, 0 ,0, 0),
    c(0, 0, 0, 0, 0, 2, 0, 2,126, 1, 0, 0, 0, 0, 0, 0),
    c(0, 3, 0, 0, 0, 1, 2, 1, 0,153, 1, 0, 0, 0, 2, 1),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0,126, 0, 0, 0, 0, 0),
    c(0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0,22, 0, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 109,0, 0, 0),
    c(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 123,0),
    c(0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 145)
  )
)

rownames(lsvm.pan) <- lbls
colnames(lsvm.pan) <- lbls

cm.lsvm.pan <- confusionMatrix(lsvm.pan, dnn = c("prediction", "reference"))
```


```{r fig.width = 8, fig.height = 8}
q2 <- visualizeConfusionMat(cm.lsvm.pan, name = colnames(lsvm.pan), title = "Pan-cancer (linear-SVM)")
q2
```

```{r}
ggsave("../slides+report/lsvm_cm_pan.png", q2, width = 8, height = 8)
```

RBF
```{r}
rbf.bin <- as.matrix(rbind(c(154, 7), c(6, 1745)))
rownames(rbf.bin) <- c("Normal", "Tumor")
colnames(rbf.bin) <- c("Normal", "Tumor")

cm.rbf.bin <- confusionMatrix(rbf.bin, dnn = c("prediction", "reference"))
cm.rbf.bin
```

```{r fig.width = 4, fig.height = 3}
q1 <- visualizeConfusionMat(cm.rbf.bin, name = colnames(lsvm.bin), title = "Binary (RBF-SVM)")
q1
```

```{r}
ggsave("../slides+report/rbf_cm_bin.png", q1, width = 4, height = 3.5)
```



```{r}
rbf.pan <- as.matrix(
  rbind(
    c(93, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1),
    c(0, 267,0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0),
    c(1, 0, 74, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0),
    c(0, 0, 0, 97, 0, 0, 0, 0, 0, 0, 0, 31,0, 0, 0, 0),
    c(0, 0, 0, 0, 43, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0),
    c(2, 0, 1, 0, 0, 131,0, 0, 5, 0, 0, 0, 1, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 82, 0, 0, 0, 0, 0, 0, 0, 0, 1),
    c(0, 0, 0, 0, 0, 0, 0,135,12, 1, 0, 0, 0, 0 ,0, 0),
    c(0, 0, 0, 0, 0, 2, 0, 2,122, 0, 0, 0, 0, 0, 0, 0),
    c(1, 4, 0, 3, 0, 1, 2, 4, 0,155, 3, 0, 0, 1, 1, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0,124, 0, 0, 0, 0, 0),
    c(0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 109,0, 0, 0),
    c(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 95, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 124,0),
    c(1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 145)
  )
)

rownames(rbf.pan) <- lbls
colnames(rbf.pan) <- lbls

cm.rbf.pan <- confusionMatrix(rbf.pan, dnn = c("prediction", "reference"))
```

```{r fig.width = 8, fig.height = 8}
q2 <- visualizeConfusionMat(cm.rbf.pan, name = colnames(rbf.pan), title = "Pan-cancer (RBF-SVM)")
q2
```

```{r}
ggsave("../slides+report/rbf_cm_pan.png", q2, width = 8, height = 8)
```


#### Random Forest
```{r}
rf.bin <- as.matrix(rbind(c(142, 6), c(16, 1746)))
rownames(rf.bin) <- c("Normal", "Tumor")
colnames(rf.bin) <- c("Normal", "Tumor")

cm.rf.bin <- confusionMatrix(rf.bin, dnn = c("prediction", "reference"))
cm.rf.bin
```

```{r fig.width = 4, fig.height = 3}
q1 <- visualizeConfusionMat(cm.rf.bin, name = colnames(rf.bin), title = "Binary (Random Forest)")
q1
```

```{r}
ggsave("../slides+report/rf_cm_bin.png", q1, width = 4, height = 3.5)
```

```{r}
rb.pan <- as.matrix(
  rbind(
    c(92, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0),
    c(0,268, 0, 0, 0, 0, 0, 2, 0, 3, 0, 0, 1, 0, 0, 0),
    c(2, 0, 70, 0, 0, 5, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0),
    c(0, 0, 0,104, 0, 0, 0, 0, 0, 0, 0,43, 0, 1, 0, 0),
    c(0, 0, 0, 0, 43, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0),
    c(3, 2, 2, 0, 0,132, 0, 0, 5, 0, 0, 0, 0, 1, 0, 0),
    c(0, 0, 0, 0, 0, 0, 82, 0, 0, 0, 0, 0, 0, 0, 0, 1),
    c(0, 0, 0, 0, 0, 0, 0,133,10, 1, 0, 0, 0, 0, 0, 0),
    c(0, 0, 1, 0, 0, 1, 0, 3,124, 0, 0, 0, 0, 0, 0, 0),
    c(0, 3, 0, 0, 0, 0, 2, 3, 0,147, 1, 0, 0, 0, 1, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 2,126, 0, 0, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0),
    c(0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,109, 0, 0, 0),
    c(0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0,  0,94, 0, 0),
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,124, 0),
    c(1, 0, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,146)
  )
)

rownames(rb.pan) <- lbls
colnames(rb.pan) <- lbls

cm.rb.pan <- confusionMatrix(rb.pan, dnn = c("prediction", "reference"))
```


```{r fig.width = 8, fig.height = 8}
q2 <- visualizeConfusionMat(cm.rb.pan, name = colnames(rb.pan), title = "Pan-cancer (linear-SVM)")
q2
```

```{r}
ggsave("../slides+report/rb_cm_pan.png", q2, width = 8, height = 8)
```























































