---
title: "KNN"
author: "Yiyang Ni"
date: "2021/12/4"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data = read.csv("../data/processed_counts.csv")
```

```{r}
label = read.csv("../data/annotation.csv")
```

```{r}
label$Type[which(label$Type == "Normal")] <- 0
label$Type[which(label$Type != 0)] <- 1
```

```{r}
library(sampling)
set.seed(6690)

train_id <- sample(label$ID, round(dim(label)[1]*0.75))

train_data <- data[data$ID %in% train_id, ]
test_data <- data[!(data$ID %in% train_id), ]

train_label <- label[data$ID %in% train_id, ]
test_label <- label[!(data$ID %in% train_id), ]
```

```{r}
total_train = merge(train_data, train_label, by = "ID")
total_test = merge(test_data, test_label, by = "ID")
total_train = total_train[, -1]
total_test = total_test[, -1]
total_train$Type = factor(total_train$Type)
total_test$Type = factor(total_test$Type)
```

```{r}
library(ggplot2)
library(lattice)
library(caret)
control <- trainControl(method = 'cv', number = 10, allowParallel = TRUE)
model <- train(Type~., total_train, 
               method = 'svmLinear',
               preProcess = c('center', 'scale'),
               trControl = control, 
               tuneLength = 1)

```

```{r}
model
```

```{r}

```

```{r}
truth <- total_test$Type
pred <- predict(model, newdata = total_test)
confusionMatrix(table(pred, truth))
```
```{r}
control <- trainControl(method = 'cv', number = 10, allowParallel = TRUE)
model_r <- train(Type~., total_train, 
               method = 'svmRadial',
               preProcess = c('center', 'scale'),
               trControl = control, 
               tuneLength = 5)
```

```{r}
model_r
```

```{r}
truth <- total_test$Type
pred_r <- predict(model_r, newdata = total_test)
confusionMatrix(table(pred_r, truth))
```

```{r}
importance <- varImp(model, scale = FALSE)
plot(importance, top=20)
```

```{r}
importance_r <- varImp(model_r, scale = FALSE)
plot(importance_r, top=20)
```

```{r}
library(mccr)
mccr(truth, pred)
```

```{r}
mccr(truth, pred_r)
```

```{r}
# saveRDS(model, file = "modelsvm.rds")
```

